spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-feign.html
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
        loggerLevel: FULL  # 해당 feign interface 가 있는 package 의 log level 이 꼭 DEBUG 여야 함.
      httpbin: # @FeignClient 에서 name 값, 전역으로 설정하려면 default
        connectTimeout: 2000
        readTimeout: 5000
        loggerLevel: FULL  # 해당 feign interface 가 있는 package 의 log level 이 꼭 DEBUG 여야 함.

line:
  bot:
    channelToken: ${line.channelToken}
    channelSecret: ${line.channelSecret}
    connectTimeout: 3000
    readTimeout: 3000
    writeTimeout: 300

home:
  bot:
    downloadPath: ${downloadPath}

google:
  tokenPath: /var/tmp/tokens
  credentialsFilePath: "classpath:credentials.json"
  appName: "Google Sheets OrderList"
  sheets:
    orderList: 1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms


---
spring:
  profiles: production
  datasource:
    url: jdbc:h2:file:/db/h2db_prod;AUTO_SERVER=true
