spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

# https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-feign.html
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 20000
        loggerLevel: FULL  # 해당 feign interface 가 있는 package 의 log level 이 꼭 DEBUG 여야 함.
      httpbin: # @FeignClient 에서 name 값, 전역으로 설정하려면 default
        connectTimeout: 2000
        readTimeout: 5000
        loggerLevel: FULL  # 해당 feign interface 가 있는 package 의 log level 이 꼭 DEBUG 여야 함.

line:
  bot:
    channelToken: ${line.channelToken}
    channelSecret: ${line.channelSecret}
    connectTimeout: 3000
    readTimeout: 3000
    writeTimeout: 300
  groups:
    family: ${to}

telegram:
  token: ${tele.token}
  botName: ${tele.botname}
  managerChatId: ${tele.managerChatId}

home:
  bot:
    downloadPath: ${downloadPath}

google:
  apiKey: apiKey
  sheets:
    orderList: sheetsId

---
spring:
  profiles: local

logging:
  level:
    root: INFO

line:
  bot:
    channelToken: dummy
    channelSecret: dummy
  groups:
    family: dummyId

home:
  bot:
    downloadPath: /var/tmp

---
spring:
  profiles: production
  datasource:
    url: jdbc:h2:file:/db/h2db_prod;AUTO_SERVER=true
